### ISSUE TITLE
Add tag option when creating vlands on a bridge 

### ISSUE THREAD

**Issue by mrtrkmn** [aau-network-security/openvswitch#3]
Seems, there is no such a function in forked project to include `tag` option to create vlan; there is no option to execute following command given below.  (adding tag to vlan (on existing bridge))

`ovs-vsctl add-port <bridge-name> <vlan-name> tag=<vlan-tag> -- set interface <vlan-name> type=internal`

Add provided feature above to library.

**Comment by mrtrkmn** [comment]
Related to #2 , check and validate result.

**Comment by Lanestolen** [comment]
The set command need to be run separat on the interface, which can be done with the following code:
``` 
ovswitch := ovs.New(ovs.Sudo())
err := ovswitch.VSwitch.AddBridge("test")
	if err != nil {
		log.Println(err)
}
err = ovswitch.VSwitch.AddPortTagged("test", "tap10", "10")
	if err != nil {
		log.Println(err)
}
err = ovswitch.VSwitch.Set.Interface("tap10", ovs.InterfaceOptions{Type: ovs.InterfaceTypeInternal})
	if err != nil {
		log.Println(err)
}
```
